-- 002_seed_couriers.sql
-- Seed data for test courier profiles

-- Insert test courier 1: Nyengo Express (Premium courier)
INSERT INTO couriers (
    id,
    email,
    password,
    company_name,
    owner_name,
    phone,
    alternate_phone,
    whatsapp,
    address,
    city,
    country,
    logo_url,
    description,
    service_areas,
    vehicle_types,
    max_weight,
    operating_hours,
    base_rate_per_km,
    minimum_fare,
    custom_pricing,
    rating,
    total_reviews,
    total_deliveries,
    success_rate,
    is_verified,
    is_active,
    is_featured,
    wallet_balance
) VALUES (
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'express@nyengo.com',
    '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36TaT0pK6.q8xNcLp3Mn/VW', -- password: password123
    'Nyengo Express',
    'John Banda',
    '+260971234567',
    '+260955123456',
    '+260971234567',
    '123 Cairo Road, Longacres',
    'Lusaka',
    'Zambia',
    'https://ui-avatars.com/api/?name=Nyengo+Express&background=4F46E5&color=fff&size=128',
    'Fast and reliable delivery service across Lusaka. Specializing in same-day deliveries with real-time tracking.',
    ARRAY['Lusaka', 'Chilanga', 'Kafue', 'Chongwe'],
    ARRAY['motorcycle', 'car', 'van'],
    100.0,
    '{"monday": {"open": "06:00", "close": "22:00", "closed": false}, "tuesday": {"open": "06:00", "close": "22:00", "closed": false}, "wednesday": {"open": "06:00", "close": "22:00", "closed": false}, "thursday": {"open": "06:00", "close": "22:00", "closed": false}, "friday": {"open": "06:00", "close": "22:00", "closed": false}, "saturday": {"open": "08:00", "close": "18:00", "closed": false}, "sunday": {"open": "09:00", "close": "15:00", "closed": false}}'::jsonb,
    3.50,
    15.00,
    true,
    4.8,
    256,
    1523,
    98.5,
    true,
    true,
    true,
    2500.00
) ON CONFLICT (email) DO NOTHING;

-- Insert test courier 2: Swift Riders (Budget-friendly)
INSERT INTO couriers (
    id,
    email,
    password,
    company_name,
    owner_name,
    phone,
    whatsapp,
    address,
    city,
    country,
    logo_url,
    description,
    service_areas,
    vehicle_types,
    max_weight,
    operating_hours,
    base_rate_per_km,
    minimum_fare,
    rating,
    total_reviews,
    total_deliveries,
    success_rate,
    is_verified,
    is_active,
    is_featured,
    wallet_balance
) VALUES (
    'b2c3d4e5-f6a7-8901-bcde-f23456789012',
    'swift@riders.zm',
    '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36TaT0pK6.q8xNcLp3Mn/VW',
    'Swift Riders',
    'Mwila Tembo',
    '+260966789012',
    '+260966789012',
    '45 Great East Road, Kabulonga',
    'Lusaka',
    'Zambia',
    'https://ui-avatars.com/api/?name=Swift+Riders&background=10B981&color=fff&size=128',
    'Affordable motorcycle delivery service. Quick pickups and deliveries for small to medium packages.',
    ARRAY['Lusaka', 'Kalingalinga', 'Mtendere', 'Garden Compound'],
    ARRAY['motorcycle'],
    25.0,
    '{"monday": {"open": "07:00", "close": "20:00", "closed": false}, "tuesday": {"open": "07:00", "close": "20:00", "closed": false}, "wednesday": {"open": "07:00", "close": "20:00", "closed": false}, "thursday": {"open": "07:00", "close": "20:00", "closed": false}, "friday": {"open": "07:00", "close": "20:00", "closed": false}, "saturday": {"open": "08:00", "close": "16:00", "closed": false}, "sunday": {"open": "00:00", "close": "00:00", "closed": true}}'::jsonb,
    2.50,
    10.00,
    4.5,
    189,
    892,
    95.2,
    true,
    true,
    false,
    1200.00
) ON CONFLICT (email) DO NOTHING;

-- Insert test courier 3: City Cargo (Heavy items specialist)
INSERT INTO couriers (
    id,
    email,
    password,
    company_name,
    owner_name,
    phone,
    alternate_phone,
    whatsapp,
    address,
    city,
    country,
    logo_url,
    description,
    service_areas,
    vehicle_types,
    max_weight,
    operating_hours,
    base_rate_per_km,
    minimum_fare,
    rating,
    total_reviews,
    total_deliveries,
    success_rate,
    is_verified,
    is_active,
    is_featured,
    wallet_balance
) VALUES (
    'c3d4e5f6-a7b8-9012-cdef-345678901234',
    'cargo@citycargo.zm',
    '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36TaT0pK6.q8xNcLp3Mn/VW',
    'City Cargo',
    'Peter Mumba',
    '+260977345678',
    '+260211234567',
    '+260977345678',
    '78 Freedom Way, Industrial Area',
    'Lusaka',
    'Zambia',
    'https://ui-avatars.com/api/?name=City+Cargo&background=F59E0B&color=fff&size=128',
    'Specialized in large and heavy cargo. Furniture, appliances, and bulk deliveries. Professional loading and unloading included.',
    ARRAY['Lusaka', 'Ndola', 'Kitwe', 'Livingstone', 'Chipata'],
    ARRAY['van', 'truck'],
    500.0,
    '{"monday": {"open": "06:00", "close": "18:00", "closed": false}, "tuesday": {"open": "06:00", "close": "18:00", "closed": false}, "wednesday": {"open": "06:00", "close": "18:00", "closed": false}, "thursday": {"open": "06:00", "close": "18:00", "closed": false}, "friday": {"open": "06:00", "close": "18:00", "closed": false}, "saturday": {"open": "07:00", "close": "14:00", "closed": false}, "sunday": {"open": "00:00", "close": "00:00", "closed": true}}'::jsonb,
    5.00,
    50.00,
    4.6,
    124,
    487,
    97.8,
    true,
    true,
    true,
    5800.00
) ON CONFLICT (email) DO NOTHING;

-- Insert test courier 4: Zam Deliveries (New courier)
INSERT INTO couriers (
    id,
    email,
    password,
    company_name,
    owner_name,
    phone,
    whatsapp,
    address,
    city,
    country,
    logo_url,
    description,
    service_areas,
    vehicle_types,
    max_weight,
    operating_hours,
    base_rate_per_km,
    minimum_fare,
    rating,
    total_reviews,
    total_deliveries,
    success_rate,
    is_verified,
    is_active,
    is_featured,
    wallet_balance
) VALUES (
    'd4e5f6a7-b8c9-0123-defa-456789012345',
    'deliveries@zamdeliveries.co.zm',
    '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36TaT0pK6.q8xNcLp3Mn/VW',
    'Zam Deliveries',
    'Grace Phiri',
    '+260955567890',
    '+260955567890',
    '234 Independence Avenue',
    'Lusaka',
    'Zambia',
    'https://ui-avatars.com/api/?name=Zam+Deliveries&background=8B5CF6&color=fff&size=128',
    'Your friendly neighborhood delivery service. We handle your packages with care!',
    ARRAY['Lusaka', 'Roma', 'Olympia', 'Northmead'],
    ARRAY['motorcycle', 'car'],
    50.0,
    '{"monday": {"open": "08:00", "close": "20:00", "closed": false}, "tuesday": {"open": "08:00", "close": "20:00", "closed": false}, "wednesday": {"open": "08:00", "close": "20:00", "closed": false}, "thursday": {"open": "08:00", "close": "20:00", "closed": false}, "friday": {"open": "08:00", "close": "20:00", "closed": false}, "saturday": {"open": "09:00", "close": "17:00", "closed": false}, "sunday": {"open": "10:00", "close": "14:00", "closed": false}}'::jsonb,
    3.00,
    12.00,
    4.2,
    45,
    156,
    93.5,
    true,
    true,
    false,
    450.00
) ON CONFLICT (email) DO NOTHING;

-- Insert test courier 5: Flash Courier (24/7 service)
INSERT INTO couriers (
    id,
    email,
    password,
    company_name,
    owner_name,
    phone,
    whatsapp,
    address,
    city,
    country,
    logo_url,
    description,
    service_areas,
    vehicle_types,
    max_weight,
    operating_hours,
    base_rate_per_km,
    minimum_fare,
    rating,
    total_reviews,
    total_deliveries,
    success_rate,
    is_verified,
    is_active,
    is_featured,
    wallet_balance
) VALUES (
    'e5f6a7b8-c9d0-1234-efab-567890123456',
    'support@flashcourier.zm',
    '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36TaT0pK6.q8xNcLp3Mn/VW',
    'Flash Courier',
    'Daniel Mwansa',
    '+260972111222',
    '+260972111222',
    '567 Addis Ababa Drive, Rhodes Park',
    'Lusaka',
    'Zambia',
    'https://ui-avatars.com/api/?name=Flash+Courier&background=EF4444&color=fff&size=128',
    '24/7 emergency and express delivery service. When it absolutely must be there fast!',
    ARRAY['Lusaka', 'Kabwata', 'Chilenje', 'Libala', 'Woodlands'],
    ARRAY['motorcycle', 'car'],
    75.0,
    '{"monday": {"open": "00:00", "close": "23:59", "closed": false}, "tuesday": {"open": "00:00", "close": "23:59", "closed": false}, "wednesday": {"open": "00:00", "close": "23:59", "closed": false}, "thursday": {"open": "00:00", "close": "23:59", "closed": false}, "friday": {"open": "00:00", "close": "23:59", "closed": false}, "saturday": {"open": "00:00", "close": "23:59", "closed": false}, "sunday": {"open": "00:00", "close": "23:59", "closed": false}}'::jsonb,
    4.50,
    20.00,
    4.7,
    312,
    1089,
    96.8,
    true,
    true,
    true,
    3200.00
) ON CONFLICT (email) DO NOTHING;
